apiVersion: v1
kind: ConfigMap
metadata:
  name: flagd-config
  namespace: train-ticket
data:
  flags.yaml: |
    flags:
      tt-feat-01:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-02:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-03:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-04:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-05:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-06:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-07:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-08:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-09:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-10:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-11:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-12:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-13:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-14:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-15:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-16:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-17:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-18:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-19:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-20:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-21:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"

      tt-feat-22:
        state: ENABLED
        variants:
          "on": true
          "off": false
        defaultVariant: "off"
