# Default values for nacos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  mode: cluster

############################nacos###########################
nacos:
  image:
    repository: ghcr.io/sregym/train-ticket-nacos
    tag: 20260911-multiarch@sha256:9e047e4285b437647c1e7ce0206d195ceb64fe23c69e2c443d285890c165b91a
    pullPolicy: IfNotPresent
  replicaCount: 3
  domainName: cluster.local
  preferhostmode: hostname
  serverPort: 8848
  health:
    enabled: false
  secretName: nacos-mysql
  db:
    name: "nacos"
    host: "nacos-mysql-leader"
    username: "nacos"
    passowrd: "Abcd1234#"
    port: "3306"
  headlessService: "nacos-headless"
service:
  #type: ClusterIP
  type: NodePort
  port: 8848

initmysql:
  image: "ghcr.io/sregym/train-ticket-mysqlclient:20260911-multiarch@sha256:d6f86c7b70c48c1360dc0e39d07e13b436bc2f111cf3ce38dc14a1ddf474e3b7"



resources:
  requests:
    cpu: 500m
    memory: 1Gi
  # limits:
  #   cpu: 1000m
  #   memory: 4Gi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.


annotations: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
